# python crawler only, extensive see pythoncrawler
version: '3.8'
services:
  python:
    build: ./dockersetup/pythoncrawler
    command: bash -c 'python autoscouter_docker.py'
    volumes:
      - ./data/autos:/autos
      - ./data/visited:/visited
    cpus: "0.5"