version: '3.8'
services:
  pythonautoscout:
    build: ./dockersetup/pythoncrawler/src/
    image: pythonautoscout:1.1
  autoscoutcrawl:
    build: ./dockersetup/pythoncrawler/
    restart: always
    container_name: autoscoutcrawler
    volumes:
      - ./data/autos:/autos
      - ./data/visited:/visited
    cpus: "0.5"