version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    volumes:
      - ./elk/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:7.9.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elastic
  python:
    build: ./pythoncrawler
    volumes:
      - ../data/autos:/autos
      - ../data/visited:/visited

networks:
  elastic:
    driver: bridge